version: '3.1'

services:
  officefood:
    depends_on:
      - officefood-db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      #OFFICE_DB_PASSWORD: masterkey
      #OFFICE_DB_USERNAME: postgres
      OFFICE_DB_PASSWORD: ${OFFICE_DB_PASSWORD}
      OFFICE_DB_USERNAME: ${OFFICE_DB_USERNAME}
    restart: always
  officefood-db:
    image: postgres
    restart: always
    container_name: db
    environment:
      #POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: masterkey
      POSTGRES_USER: ${OFFICE_DB_USERNAME}
      POSTGRES_PASSWORD: ${OFFICE_DB_PASSWORD}
      POSTGRES_DB: "officefood"
    ports:
      - "5416:5432"