CREATE TABLE public.lunch_menu
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cost numeric(19,2),
    name character varying(255),
    short_name character varying(255),
    uniq_code character varying(255),
    CONSTRAINT lunch_menu_pkey PRIMARY KEY (id)
)
