CREATE TABLE public.lunch_tg_users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    chat_id  character varying(100),
    active boolean,
    CONSTRAINT lunch_tg_users_pkey PRIMARY KEY (id)
)

